### ISSUE TITLE
Large file size uploads

### ISSUE THREAD

**Issue by gulalicelik** [hidayet-aydin/azure-storage-manager#1]
When trying to upload a large file, it prints the` Uploaded: fileName.pdf` log as soon as it starts to be uploaded. When the file is uploaded, this log can be printed or the current uploaded file can be displayed dynamically like "Uploading".This improvement can prevent possible user errors that may occur during the upload of large files.

**Comment by hidayet-aydin** [comment]
Your request has been implemented. "Uploading" log is created when file starts uploading and "Uploaded" log is created when upload is complete. Downloading follows the same order as uploading ("Downloading" -> "Downloaded")
